pinned hatch + click versions in the pipx environment due to bug
There was a bug in hatch + click 8.2 such that `hatch run python --version` raised the following error:

```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/hatch/cli/__init__.py:221 │
│ in main                                                                      │
│                                                                              │
│   218                                                                        │
│   219 def main():  # no cov                                                  │
│   220 │   try:                                                               │
│ ❱ 221 │   │   hatch(prog_name='hatch', windows_expand_args=False)            │
│   222 │   except Exception:  # noqa: BLE001                                  │
│   223 │   │   import sys                                                     │
│   224                                                                        │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/core.py:1462 in     │
│ __call__                                                                     │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/core.py:1383 in     │
│ main                                                                         │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/core.py:1850 in     │
│ invoke                                                                       │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/core.py:1246 in     │
│ invoke                                                                       │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/core.py:814 in      │
│ invoke                                                                       │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/decorators.py:34 in │
│ new_func                                                                     │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/hatch/cli/run/__init__.py │
│ :147 in run                                                                  │
│                                                                              │
│   144 │   elif not env_name:                                                 │
│   145 │   │   env_name = 'system'                                            │
│   146 │                                                                      │
│ ❱ 147 │   ctx.invoke(                                                        │
│   148 │   │   run_command,                                                   │
│   149 │   │   args=[command, *final_args],                                   │
│   150 │   │   env_names=[env_name],                                          │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/core.py:814 in      │
│ invoke                                                                       │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/click/decorators.py:46 in │
│ new_func                                                                     │
│                                                                              │
│ /opt/pipx/venvs/hatch/lib/python3.11/site-packages/hatch/cli/env/run.py:123  │
│ in run                                                                       │
│                                                                              │
│   120 │   if filter_json:                                                    │
│   121 │   │   import json                                                    │
│   122 │   │                                                                  │
│ ❱ 123 │   │   filter_data = json.loads(filter_json)                          │
│   124 │   │   if not isinstance(filter_data, dict):                          │
│   125 │   │   │   app.abort('The --filter/-f option must be a JSON mapping') │
│   126                                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/json/__init__.py:339  │
│ in loads                                                                     │
│                                                                              │
│   336 │   │   │   │   │   │   │   │     s, 0)                                │
│   337 │   else:                                                              │
│   338 │   │   if not isinstance(s, (bytes, bytearray)):                      │
│ ❱ 339 │   │   │   raise TypeError(f'the JSON object must be str, bytes or by │
│   340 │   │   │   │   │   │   │   f'not {s.__class__.__name__}')             │
│   341 │   │   s = s.decode(detect_encoding(s), 'surrogatepass')              │
│   342                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: the JSON object must be str, bytes or bytearray, not Sentinel
```